org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
systemProp.java.net.preferIPv4Stack=true
systemProp.java.net.preferIPv6Addresses=false
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
